#!/bin/bash
backlight_dir="/sys/class/backlight/radeon_bl0"
brightness_file="$backlight_dir/brightness"
min_brightness=0
max_brightness=$(cat "$backlight_dir/max_brightness")


set_raw_brightness() {
    if [ $1 -ge $min_brightness ] && [ $1 -le $max_brightness ]
    then
        echo $1 | tee "$brightness_file"
    else
        echo "Invalid brightness value"
    fi
}

set_brightness() {
    new_brightness=$(get_percent $1 $max_brightness)
    set_raw_brightness $new_brightness
}

calculate_percent() {
    percent_f=$(echo "scale=2;$1 / $2 * 100" | bc)
    echo $(echo "$percent_f / 1" | bc)
}

get_percent() {
    percent_f=$(echo "scale=2;$1 * $2 / 100" | bc)
    echo $(echo "$percent_f / 1" | bc)
}

get_raw_brightness() {
    echo $(cat $brightness_file)
}

get_brightness() {
    raw_brightness=$(get_raw_brightness)
    echo $(calculate_percent $raw_brightness $max_brightness)
}


change_brightness() {
    case $1 in
        -inc)
            op='+'
            ;;
        -dec)
            op='-'
            ;;
    esac
    before=$(get_brightness)
    after=$(expr "$before" $op "$2")
    set_brightness $after
}

print_usage() {
    echo "Usage:
    -set <value>
    -inc <value>
    -dec <value>
    -setr <value>"
}


if [ $# -eq 0 ]
then
    get_brightness
    exit
elif [ $# -eq 2 ]
then
    case $1 in
        -set)
            set_brightness $2
            ;;
        -setr)
            set_raw_brightness $2
            ;;
        -inc|-dec)
            change_brightness $1 $2
            ;;
        *)
            print_usage
            ;;
    esac
else
    print_usage
fi
