#!/bin/bash
backlight_dir="/sys/class/backlight/radeon_bl0"
brightness_file="$backlight_dir/brightness"
min_brightness=0
max_brightness=$(cat "$backlight_dir/max_brightness")
if [ $# -eq 0 ]
then
    cat "$brightness_file"
    exit
elif [ $# -eq 2 ] && [ "$1" = "-set" ]
    then
    if [ $2 -ge 0 ] && [ $2 -le $max_brightness ]
    then
        echo $2 | tee "$brightness_file"
    else
        echo "Invalid brightness value"
    fi
else
    echo "Usage:
    -set <value>"
fi
